---
# tasks file for pgadmin_role
- name: generate docker compose
  template:
    src : "docker-compose.pgadmin.yaml.j2"
    dest: "/home/{{ ansible_user }}/docker-compose.pgadmin.yaml"
    mode: "0555"

- name: start compose
  command: "docker compose -f /home/{{ ansible_user }}/docker-compose.pgadmin.yaml up -d"

- name: stop compose pgadmin
  command: "docker compose -f /home/{{ ansible_user }}/docker-compose.pgadmin.yaml down -v"
  tags: delete