apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  labels:
    env: prod
spec:
  selector:
    app: pgadmin
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 80
  type: LoadBalancer