apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-deployment
  labels:
    app: postgresql
    env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
      env: prod
  template:
    metadata:
      labels:
        app: postgresql
        env: prod
    spec:
      containers:
      - name: postgresql
        image: postgres:15
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
            name: postgresql-secret
        # env:
        # - name: POSTGRES_DB
        #   value: postgres
        # - name: POSTGRES_USER
        #   value: odoo
        # - name: POSTGRES_PASSWORD
        #   value: odoo
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi
      storageClassName: local-path
