pipeline{
    agent any
    environment {
        DOCKERFILE_NAME = "Dockerfile"
        DOCKER_DIR = "./01_docker"
        IMAGE_NAME = "ic-webapp"
        IMAGE_TAG = "1.0"
        DOCKERHUB_ID = "ulrichsteve"
        HOST_PORT = "8080"
        CONT_PORT = "8080"
        HOST_IP = ""
        DOCKERHUB_PASSWORD = credentials('dockerhub_password')
    }
    stages{
        stage("Build Image"){
            steps{
                script {
                    sh '''
                        docker build  --no-cache -t ${DOCKERHUB_ID}/${IMAGE_NAME}:${IMAGE_TAG} -f ${DOCKER_DIR}/${DOCKERFILE_NAME} ${DOCKER_DIR}/.
                    '''
                }
            }
        }
        stage("Run and Test"){
            steps{
                script {
                    sh '''
                        docker ps -a | grep -i ${IMAGE_NAME} && docker rm -f ${IMAGE_NAME}
                        docker run --name ${IMAGE_NAME} -dp $HOST_PORT:$CONT_PORT  ${DOCKERHUB_ID}/${IMAGE_NAME}:${IMAGE_TAG}
                        sleep 5
                        curl -I http://$HOST_IP:$HOST_PORT | grep -i "200"
                    '''
                }
            }
        }
        // stage("Push Image"){
        //     steps{
        //         script {
        //             sh '''
        //                 docker build -t ic-webapp:1.0 .
        //             '''
        //         }
        //     }
        // }
        // stage("Build Image"){
        //     steps{
        //         script {
        //             sh '''
        //                 echo ${DOCKERHUB_PASSWORD} | docker login -u ${DOCKERHUB_ID} --password-stdin
        //                 docker push ${DOCKERHUB_ID}/${IMAGE_NAME}:${IMAGE_TAG}
        //             '''
        //         }
        //     }
        // }
    }
    // post{
    //     always{
    //         echo "========always========"
    //     }
    //     success{
    //         echo "========pipeline executed successfully ========"
    //     }
    //     failure{
    //         echo "========pipeline execution failed========"
    //     }
    // }
}