---
# tasks file for odoo_role
- name: generate docker compose
  template:
    src : "docker-compose.odoo.yaml.j2"
    dest: "/home/{{ ansible_user }}/docker-compose.odoo.yaml"
    mode: "0555"

- name: start compose
  command: "docker compose -f /home/{{ ansible_user }}/docker-compose.odoo.yaml up -d"


- name: stop compose odoo
  command: "docker compose -f /home/{{ ansible_user }}/docker-compose.odoo.yaml down -v "
  tags: delete